#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Bingo-Print
version:      0.02
version_from: lib/Games/Bingo/Print.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    Games::Bingo:                  0.09
    PDFLib:                        0.12
    Test::Harness:                 0
    Test::Pod:                     0.95
    Data::Dumper:                  0
    Test::More:                    0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
